export default{
    //改变主题
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    
    //github页面更新
    POPULAR_REFRESH: "POPULAR_REFRESH",
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",
    POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",
}